"""Invoice email sender. Falls back to local outbox HTML files."""

from datetime import datetime
from email.message import EmailMessage
from base64 import b64encode
import smtplib
from pathlib import Path

from config import Config, OUTBOX_DIR, POSCO_CI_PATH


def parse_emails(raw: str) -> list[str]:
    if not raw:
        return []
    parts = raw.replace("\n", ";").replace(",", ";").split(";")
    return [p.strip() for p in parts if p.strip() and "@" in p]


def hq_copy_emails() -> list[str]:
    return parse_emails(getattr(Config, "HQ_COPY_EMAIL", "") or "")


def send_invoice_email(
    invoice,
    pdf_path: Path,
    remind: bool = False,
    updated: bool = False,
    extra_recipients=None,
    hq_only: bool = False,
) -> dict:
    if hq_only:
        recipients = hq_copy_emails()
    else:
        recipients = parse_emails(invoice.subsidiary.emails)
        extras = list(extra_recipients or [])
        extras.extend(hq_copy_emails())
        for email in extras:
            if email and email not in recipients:
                recipients.append(email)
    if not recipients:
        return {"ok": False, "error": "no_email", "recipients": []}

    if hq_only:
        subject = f"[HQ Copy] POSCO Group University Invoice {invoice.invoice_no}"
        headline = "HQ Copy — Issued Invoice"
    elif remind:
        subject = f"[Reminder] POSCO Group University Invoice {invoice.invoice_no}"
        headline = "Payment / Acknowledgement Reminder"
    elif updated:
        subject = f"[Updated] POSCO Group University Invoice {invoice.invoice_no}"
        headline = "Updated Invoice"
    else:
        subject = f"POSCO Group University Invoice {invoice.invoice_no}"
        headline = "Education Service Invoice"

    period = f"{invoice.period_start.strftime('%Y-%m-%d')} ~ {invoice.period_end.strftime('%Y-%m-%d')}"
    program_html = "".join(
        f"<tr><td>{it.description}</td><td>{(it.period_start or invoice.period_start).strftime('%Y-%m-%d')} ~ {(it.period_end or invoice.period_end).strftime('%Y-%m-%d')}</td><td>{it.qty}</td></tr>"
        for it in (invoice.items or [])
    ) or f"<tr><td>{invoice.education_name}</td><td>{period}</td><td>{invoice.qty}</td></tr>"
    ci_img = ""
    if POSCO_CI_PATH.exists():
        ci_b64 = b64encode(POSCO_CI_PATH.read_bytes()).decode("ascii")
        ci_img = (
            f'<img src="data:image/png;base64,{ci_b64}" alt="POSCO" '
            'height="22" style="height:22px;display:block;margin-bottom:8px">'
        )
    body_html = f"""
    <div style="font-family:Calibri,'Segoe UI',Arial,sans-serif;color:#1b2a4e;line-height:1.5">
      <div style="background:#002060;color:#fff;padding:16px 20px">
        {ci_img}
        <div style="font-size:12px;letter-spacing:1px">POSCO GROUP UNIVERSITY</div>
        <div style="font-size:20px;font-weight:700">{headline}</div>
      </div>
      <div style="padding:20px;background:#F0F4F8">
        <p>{"Dear PGU Coordinator," if hq_only else "Dear Finance / Training Coordinator,"}</p>
        <p>{"This is a copy of an issued invoice for PGU internal records." if hq_only else "Please find attached the official English invoice issued by POSCO Group University."}</p>
        <table style="border-collapse:collapse;background:#fff" cellpadding="8">
          <tr><td>Reference No.</td><td><b>{invoice.invoice_no}</b></td></tr>
          <tr><td>Billed Entity</td><td>{invoice.subsidiary.name_en}</td></tr>
          <tr><td>Education Service</td><td>{invoice.education_name}</td></tr>
          <tr><td colspan="2">
            <table style="width:100%;border-collapse:collapse" cellpadding="6">
              <tr><th align="left">Program</th><th align="left">Period</th><th align="left">Qty</th></tr>
              {program_html}
            </table>
          </td></tr>
          <tr><td>Net Aggregate Due</td><td><b>{invoice.currency} {float(invoice.amount_fx):,.2f}</b></td></tr>
          <tr><td>VAT</td><td>Exempt 0%</td></tr>
        </table>
        <p>{"Please keep this copy for PGU internal records." if hq_only else "Kindly review the details in the overseas entity portal and click <b>Acknowledge</b> after confirmation. Please quote the Reference No. on your wire transfer."}</p>
        <p>BIC (Swift Code): {Config.BANK_SWIFT} · {Config.BANK_NAME}, {Config.BANK_BRANCH}</p>
        <p style="color:#5B6770;font-size:12px">This message was generated by the PGU Education Invoice Portal.</p>
      </div>
    </div>
    """

    OUTBOX_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    suffix = "_hq" if hq_only else ""
    out_file = OUTBOX_DIR / f"{invoice.invoice_no}{suffix}_{stamp}.html"
    out_file.write_text(
        f"<!-- To: {', '.join(recipients)} -->\n<!-- Subject: {subject} -->\n{body_html}",
        encoding="utf-8",
    )
    pdf_file = Path(pdf_path) if pdf_path else None
    pdf_bytes = pdf_file.read_bytes() if pdf_file and pdf_file.exists() else b""
    if pdf_bytes:
        (OUTBOX_DIR / f"{invoice.invoice_no}{suffix}_{stamp}.pdf").write_bytes(pdf_bytes)

    sent_via = "outbox"
    error = None
    if Config.MAIL_ENABLED:
        if not (Config.MAIL_HOST and Config.MAIL_FROM):
            return {
                "ok": False,
                "error": "smtp_not_configured",
                "recipients": recipients,
                "via": "outbox",
                "outbox": str(out_file),
            }
        try:
            msg = EmailMessage()
            msg["Subject"] = subject
            msg["From"] = Config.MAIL_FROM
            msg["To"] = ", ".join(recipients)
            msg.set_content(
                f"Please find attached invoice {invoice.invoice_no}. "
                f"Net due: {invoice.currency} {float(invoice.amount_fx):,.2f}"
            )
            msg.add_alternative(body_html, subtype="html")
            if pdf_bytes:
                msg.add_attachment(
                    pdf_bytes,
                    maintype="application",
                    subtype="pdf",
                    filename=f"{invoice.invoice_no}.pdf",
                )
            with smtplib.SMTP(Config.MAIL_HOST, int(Config.MAIL_PORT or 587), timeout=20) as smtp:
                if getattr(Config, "MAIL_USE_TLS", True):
                    smtp.starttls()
                if Config.MAIL_USERNAME:
                    smtp.login(Config.MAIL_USERNAME, Config.MAIL_PASSWORD)
                smtp.send_message(msg)
            sent_via = "smtp"
        except Exception as exc:  # noqa: BLE001
            return {
                "ok": False,
                "error": str(exc),
                "recipients": recipients,
                "via": "outbox",
                "outbox": str(out_file),
            }

    return {
        "ok": True,
        "recipients": recipients,
        "via": sent_via,
        "outbox": str(out_file),
        "error": error,
    }
